name: Build and Test

on:
  push:
    branches:
      - dev 
      - master
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true 

      - name: Set env
        if: github.event_name == 'release'
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Print Release Version
        if: github.event_name == 'release'
        run: |
          echo "Release Version: $RELEASE_VERSION"
          echo "Release Version from env: ${{ env.RELEASE_VERSION }}"

      - name: Update FPTN_VERSION in conanfile.py
        if: github.event_name == 'release'
        run: |
          sed -i "s/^FPTN_VERSION = \".*\"/FPTN_VERSION = \"$RELEASE_VERSION\"/" conanfile.py

      - name: TEST
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          cat conanfile.py
      
      - name: Upload server-deb
        if: github.event.action == 'release'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path:  conanfile.py

      # - name: Install dependencies
      #   run: |
      #     conan install . --output-folder=build --build=missing

      # - name: Build
      #   run: |
      #     cd build
      #     cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
      #     cmake --build .
      
      # - name: Test
      #   run: |
      #     cd build
      #     ctest

      # - name: Build Debian package
      #   run: |
      #     cd build
      #     cmake --build . --target build-deb

      # - name: Upload client-deb
      #   if: github.event.action == 'release'
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path:  fptn-client-cli-*.deb
      
      # - name: Upload server-deb
      #   if: github.event.action == 'release'
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path:  fptn-server-*.deb
