name: Build and Test

on:
  push:
    branches:
      - dev 
      - master
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true 

      - name: Set env
        if: github.event_name == 'release'
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Print Release Version
        if: github.event_name == 'release'
        run: |
          echo "Release Version: $RELEASE_VERSION"
          echo "Release Version from env: ${{ env.RELEASE_VERSION }}"

      - name: Update FPTN_VERSION in conanfile.py
        if: github.event_name == 'release'
        run: |
          sed -i "s/^FPTN_VERSION = \".*\"/FPTN_VERSION = \"$RELEASE_VERSION\"/" conanfile.py
    
      - name: Upload deb
        if: github.event_name == 'release'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "fptn-*.deb"
          repo-token: ${{ secrets.CI_TOKEN }}
          
