name: Build and Test

on:
  push:
    branches:
      - dev 
      - master
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
          - Ubuntu
          - macOS
          - Windows

jobs:
  build:
    runs-on: ${{ inputs.chosen-os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true 

      - name: Install dependencies
        run: |
          conan install . --output-folder=build --build=missing

      - name: Build
        run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      
      - name: Test
        run: |
          cd build
          ctest

      - name: Build Debian package
        run: |
          cd build
          cmake --build . --target build-deb
